"use client";
import { useState, useRef } from "react";
import Link from "next/link";
import type { Case, Key } from "@/lib/types";
import { keys, labels } from "@/lib/types";
import { panama, display, readable } from "@/lib/format";
import { Heading, Notices, Badge, Citation, External, GenerationNote, ValidationNote, TextList } from "./shared";
import Sentences from "./sentences";
const tabs = ["Evento", "Fuentes", "Evidencia", "Afirmaciones", "Conflictos", "Vacíos", "Producir", "Revisión"];
export default function CaseView({event: e, weights}: {event: Case; weights: Record<Key, number>}) {
  const [tab, setTab] = useState(0); const refs = useRef<(HTMLButtonElement | null)[]>([]);
  const p = e.package;
  const resolve = (ids: string[]) => ids.map(id => e.claims.find(c => c.claim_id === id)?.statement ?? id);
  return <><Link href="/" className="muted">← Sala de Situación</Link><div style={{marginTop:22}}><Heading section={`${e.event_id} · ${readable(e.topic)}`} title={e.title}/></div><div className="badges"><Badge value={e.priority.tier}/><Badge value={e.evidence_status}/>{e.synthetic ? <Badge value="SINTÉTICO"/> : null}<span className="muted">{e.priority.rules_version}</span></div><Notices/><section className="card score-panel"><div><p className="eyebrow">Atención editorial</p><div className="score-large">{e.priority.score}</div><p className="muted">de 100 puntos</p></div><div className="component-grid">{keys.map(k => <div className="component" key={k}><strong>{k} · {labels[k]}</strong><p>{e.contributions[k].toLocaleString("es-PA",{maximumFractionDigits:4})} / {weights[k]} puntos</p><progress max={1} value={e.priority.components[k]} aria-label={`${labels[k]}: ${e.priority.components[k]}`}/><p>{e.priority.components.rationale[k]}</p></div>)}</div></section><p><strong>Evidencia:</strong> {e.evidence_status_reason}</p><p className="action">{e.recommended_action}</p>{e.text_scope_note ? <p className="warning">{e.text_scope_note}</p> : null}{e.is_recirculated ? <p className="warning">Noticia recirculada: se conserva la fecha original de publicación.</p> : null}{e.temporal_warnings.map(w => <p className="warning" key={w.evidence_id}>{w.message}</p>)}{e.security_flags.map((flag,i) => <p className="warning" key={i}>Fuente con instrucciones sospechosas, tratada como dato · {flag}</p>)}<div className="tabs" role="tablist" aria-label="Secciones de la ficha">{tabs.map((name,i) => <button key={name} ref={node=>{refs.current[i]=node;}} id={`tab-${i}`} role="tab" aria-selected={tab===i} tabIndex={tab===i ? 0 : -1} aria-controls="case-panel" onClick={()=>setTab(i)} onKeyDown={ev=>{let next=i;if(ev.key==="ArrowRight")next=(i+1)%tabs.length;else if(ev.key==="ArrowLeft")next=(i+tabs.length-1)%tabs.length;else if(ev.key==="Home")next=0;else if(ev.key==="End")next=tabs.length-1;else return;ev.preventDefault();setTab(next);refs.current[next]?.focus();}}>{name}</button>)}</div><div id="case-panel" role="tabpanel" aria-labelledby={`tab-${tab}`} tabIndex={0}>
    {tab===0 ? <><div className="grid-two"><article className="card"><h2>Evento</h2><p>Tema: {readable(e.topic)}</p><h3 style={{marginTop:16}}>Entidades mencionadas</h3><TextList items={e.entities}/></article><article className="card"><h2>Línea de tiempo</h2><div className="timeline"><p>Primera publicación<br/><strong>{panama(e.first_published)}</strong></p><p>Última publicación<br/><strong>{panama(e.last_published)}</strong></p><p>Primera detección<br/><strong>{panama(e.first_detected)}</strong></p></div><p className="muted">Hora de Panamá. Publicación y detección son fechas diferentes.</p></article></div><section><h2>Titulares del evento</h2>{e.headlines.map(h=><article className="card" style={{marginBottom:12}} key={h.id_noticia}><p className="eyebrow">{h.medio} · {h.idioma}</p><h3>{h.titulo}</h3><p className="muted">Publicación: {panama(h.fecha_publicacion)} Panamá · Origen: {h.origen}</p><External url={h.url}>Abrir fuente</External>{h.origen==="sintetico" ? <Badge value="SINTÉTICO"/> : null}</article>)}</section></> : null}
    {tab===1 ? <><h2>Source DNA · procedencia</h2><div className="kpis">{[["Publicaciones",e.source_dna.publications],["Medios",e.source_dna.outlets],["Máx. independientes",e.source_dna.max_possible_independent],["Confirmadas",e.source_dna.confirmed_independent]].map(([label,value])=><div className="kpi" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="warning">N publicaciones ≠ N confirmaciones</p><p className="warning">{e.source_dna.statement}</p><div className="grid-two">{e.source_dna.groups.map(g=><article className="card" key={g.group_id}><p className="eyebrow">{g.group_id}</p><h3>{readable(g.label)}</h3><p>{g.basis}</p><TextList items={g.member_ids.map(id=>e.headlines.find(h=>h.id_noticia===id)?.titulo ?? id)}/></article>)}</div></> : null}
    {tab===2 ? <><h2>Evidencia oficial</h2><p className="muted">El contexto oficial no confirma por sí mismo el titular. Inspecciona campo, valor y período.</p>{e.official_evidence.length ? e.official_evidence.map((r,i)=><Citation key={i} refData={r}/>) : <p className="empty">No hay evidencia oficial vinculada a este caso.</p>}</> : null}
    {tab===3 ? <><h2>Afirmaciones y estado de sustento</h2>{e.claims.map(c=><article className="card" key={c.claim_id} style={{marginBottom:16}}><small>{c.claim_id}</small><div className="badges"><Badge value={c.type}/><Badge value={c.status}/></div><h3>{c.statement}</h3><p>{c.reason}</p><p className="muted">Atribución: {display(c.attributed_to)}</p>{c.temporal_note ? <p className="warning">{c.temporal_note}</p> : null}{c.evidence.map((r,i)=><Citation key={i} refData={r}/>)}</article>)}</> : null}
    {tab===4 ? <><h2>Conflictos · verificación pendiente</h2>{e.conflicts.length ? e.conflicts.map(c=><article key={c.conflict_id}><p>{c.conflict_id} · {c.kind} · {c.field} · {readable(c.status)}</p><div className="grid-two">{[["Versión A",c.version_a],["Versión B",c.version_b]].map(([label,v])=>{const version=v as typeof c.version_a;return <div className="card" key={String(label)}><h3>{String(label)}</h3><p className="stat">{display(version.value)}</p>{version.evidence.map((r,i)=><Citation key={i} refData={r}/>)}</div>;})}</div><p className="warning">{c.verification_needed}</p></article>) : <p className="empty">No hay conflictos registrados en este caso.</p>}</> : null}
    {tab===5 ? <><h2>Vacíos de investigación</h2><div className="grid-two">{[["Qué sabemos",resolve(e.gap.we_know)],["Qué se afirma",resolve(e.gap.it_is_claimed)],["Qué inferimos",resolve(e.gap.we_infer)],["Qué no sabemos",e.gap.we_dont_know],["Tres preguntas a investigar",e.gap.investigate_next]].map(([label,items])=><article className="card" key={String(label)}><h3>{String(label)}</h3><TextList items={items as string[]}/></article>)}</div></> : null}
    {tab===6 ? <><h2>Paquete editorial · borrador</h2>{p ? <><GenerationNote meta={p.generated_by}/><p className="warning">{p.scope_disclaimer}</p><article className="card"><p className="eyebrow">Título propuesto</p><h3>{p.proposed_title}</h3><p style={{marginTop:12}}><strong>Ángulo de interés público:</strong> {p.public_interest_angle}</p></article><section><h3>Brief editorial</h3><Sentences sentences={p.brief} claims={e.claims}/></section><section><h3>Guion</h3><Sentences sentences={p.script} claims={e.claims}/></section><section><h3>Copy social</h3><Sentences sentences={[p.social_copy]} claims={e.claims}/></section><div className="grid-two"><article className="card"><h3>Preguntas de investigación</h3><TextList items={p.investigation_questions}/></article><article className="card"><h3>Verificaciones pendientes</h3><TextList items={p.pending_verifications}/></article></div><section><h3>Fuentes del paquete</h3>{p.sources.map((r,i)=><Citation key={i} refData={r}/>)}</section><ValidationNote report={p.validation}/></> : <p className="empty">No hay un paquete precalculado para este caso. Puedes abrir la versión de trabajo en Streamlit.</p>}</> : null}
    {tab===7 ? <article className="card"><h2>Revisión humana</h2><p>La revisión humana se registra en la versión de trabajo; en esta demo pública es de solo lectura.</p><p className="warning">Aprobado como borrador NO significa publicado.</p><External url="https://scayl-demo.streamlit.app/">Abrir versión de trabajo</External></article> : null}
  </div></>;
}
