import type { ReactNode } from "react";
import type { Evidence, Generation, Validation } from "@/lib/types";
import { display, panama, readable, safeUrl } from "@/lib/format";
export function External({url, children}: {url: string | null; children: ReactNode}) { const href = safeUrl(url); return href ? <a href={href} target="_blank" rel="noopener noreferrer">{children} ↗</a> : <span>{children} · enlace no disponible</span>; }
export function Heading({section, title, children}: {section: string; title: string; children?: ReactNode}) { return <div className="heading"><p className="eyebrow">{section}</p><h1>{title}</h1>{children ? <p className="lede">{children}</p> : null}</div>; }
export function Notices() { return <aside className="notices"><p><strong>P mide atención</strong>, no probabilidad de verdad ni impacto. El estado de evidencia es independiente.</p><p>Prioridad alta NO habilita publicación. Aprobado como borrador NO significa publicado.</p></aside>; }
export function Badge({value, type = "evidence"}: {value: string; type?: string}) { return <span className={`badge ${type} ${value}`}>{readable(value)}</span>; }
export function Citation({refData}: {refData: Evidence}) { return <details className="citation"><summary>{display(refData.value)} <span>{refData.evidence_id} · {refData.field}</span></summary><dl><dt>Identificador</dt><dd>{refData.evidence_id}</dd><dt>Tipo / campo</dt><dd>{refData.kind} / {refData.field}</dd><dt>Valor</dt><dd>{display(refData.value)}</dd><dt>Período</dt><dd>{display(refData.period)}</dd><dt>Extracto</dt><dd>{display(refData.excerpt)}</dd><dt>URL</dt><dd><External url={refData.url}>{display(refData.url)}</External></dd></dl>{refData.evidence_id.startsWith("wb:") && refData.period ? <p className="warning">Dato histórico — {refData.period}. No presentarlo como medición actual.</p> : null}</details>; }
const modeInfo: Record<string, [string, string]> = {
  template: ["Plantilla · sin IA generativa", "Esta salida se construyó con una plantilla a partir de la evidencia disponible; no fue redactada por un modelo generativo."],
  cache: ["IA local precalculada · no es inferencia en vivo", "Esta salida se generó antes con un modelo local y se conserva para reproducir la demo; no se genera de nuevo al abrir esta página."],
  live: ["IA en vivo · modelo local", "Esta salida se generó en esta solicitud con un modelo local. Revisa sus citas antes de usarla."],
};
export function GenerationNote({meta, abstained = false}: {meta: Generation; abstained?: boolean}) { const [label, help] = modeInfo[meta.mode] ?? [`Modo ${meta.mode}`, "Modo de generación no reconocido por esta interfaz; trátalo como no verificado."]; return <div className="generation"><strong>{abstained ? "Abstención explícita · " : ""}{label}</strong><p>Modo: {meta.mode} · Modelo: {meta.model ?? "no aplica"}</p><p>{help}</p><small>{panama(meta.created_at)} Panamá · Prompt: {display(meta.prompt_version)}</small></div>; }
export function ValidationNote({report}: {report: Validation}) { return <details className="citation"><summary>Validación {report.passed ? "aprobada" : "no aprobada"} · {report.issues.length} observaciones</summary>{report.issues.map((issue, i) => <p key={i}><strong>{issue.code}</strong> · {issue.detail}</p>)}</details>; }
export function TextList({items}: {items: string[]}) { return items.length ? <ul className="text-list">{items.map((item, i) => <li key={i}>{item}</li>)}</ul> : <p className="muted">No disponible en los datos de esta demo.</p>; }
