"use client";
import {useState} from "react";
import Link from "next/link";
import {keys, labels, type Summary, type Key} from "@/lib/types";
import {simulate, adjust} from "@/lib/simulate";
import {Heading, Notices, Badge} from "./shared";
export default function Simulator({events,official}: {events:Summary[];official:Record<Key,number>}) {
  const [weights,setWeights]=useState(official);
  const rows=simulate(events,weights);const positions=new Map(events.map((e,i)=>[e.event_id,i+1]));
  const isOfficial=keys.every(k=>weights[k]===official[k]);
  return <><Heading section="Una decisión editorial explicable" title="Simulador de pesos">Explora cómo cambia la agenda al cambiar los pesos. Esta simulación no cambia el ranking oficial (scoring-v1) ni el estado de evidencia.</Heading><Notices/><section className="card"><p className="eyebrow">P = wR·R + wI·I + wU·U + wN·N + wE·E</p><h2>¿Qué merece más atención?</h2><div className="component-grid">{keys.map(k=><label className="component" key={k}><strong>{k} · {labels[k]}</strong><p className="stat">{weights[k]}</p><input aria-label={`${labels[k]} (${k})`} type="range" min={0} max={100} step={1} value={weights[k]} onChange={e=>setWeights(w=>adjust(w,k,Number(e.target.value)))}/><span className="muted">Oficial: {official[k]}</span></label>)}</div><p className="muted" style={{marginTop:20}}>Suma: {keys.reduce((s,k)=>s+weights[k],0)} / 100. Al mover un peso, se redistribuye la diferencia entre los demás (R, I, U, N, E) para conservar la suma.</p><button className="button secondary" onClick={()=>setWeights(official)}>Restablecer pesos oficiales</button><p className="warning" aria-live="polite">{isOfficial ? "Pesos oficiales del reto (scoring-v1)." : "Pesos simulados · no modifica la agenda oficial."}</p></section><section><h2>Orden oficial vs simulado</h2><p className="muted">Desempate: mayor U, luego identificador ascendente. Puntaje redondeado a una decimal como en Python.</p><div className="table-wrap"><table><thead><tr>{["Simulado", "Oficial", "Cambio", "Caso", "P oficial", "P simulado", "Rango simulado", "Evidencia"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(({event:e,score},i)=>{const before=positions.get(e.event_id)!;const delta=before-(i+1);return <tr key={e.event_id}><td className="numeric">{i+1}</td><td>{before}</td><td>{delta===0 ? "=" : delta>0 ? `↑ ${delta}` : `↓ ${-delta}`}</td><td className="title-cell"><small>{e.event_id}</small><br/><Link href={`/caso/${e.event_id}/`}>{e.title}</Link></td><td>{e.priority.score}</td><td className="numeric">{score}</td><td><Badge value={score>=70 ? "alto" : score>=40 ? "medio" : "bajo"}/></td><td><Badge value={e.evidence_status}/></td></tr>;})}</tbody></table></div></section></>;
}
