"use client";
import { useState } from "react";
import Link from "next/link";
import type { Summary } from "@/lib/types";
import { Badge } from "./shared";
import { panama, readable } from "@/lib/format";
const states = ["insuficiente", "parcial", "suficiente_para_borrador"];
export default function Situation({events}: {events: Summary[]}) {
  const [search, setSearch] = useState(""); const [topic, setTopic] = useState(""); const [status, setStatus] = useState("");
  const filtered = events.filter(e => (!topic || e.topic === topic) && (!status || e.evidence_status === status) && e.title.toLocaleLowerCase("es").includes(search.toLocaleLowerCase("es")));
  return <><section><p className="eyebrow">Explorar el snapshot</p><h2>Todos los eventos</h2><div className="filters"><label>Buscar titular<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Canal, economía, servicios…" type="search"/></label><label>Tema<select value={topic} onChange={e => setTopic(e.target.value)}><option value="">Todos los temas</option>{Array.from(new Set(events.map(e => e.topic))).sort().map(t => <option key={t} value={t}>{readable(t)}</option>)}</select></label><label>Estado de evidencia<select value={status} onChange={e => setStatus(e.target.value)}><option value="">Todos los estados</option>{states.map(s => <option key={s} value={s}>{readable(s)}</option>)}</select></label></div><p className="muted" aria-live="polite">{filtered.length} de {events.length} eventos · Orden oficial: P ↓, U ↓, ID ↑</p><div className="table-wrap"><table><thead><tr>{["Caso / titular", "P / rango", "Evidencia", "Tema", "Publicación / detección (Panamá)", "Publicaciones", "Máx. independientes", "Confirmadas", "Conflicto", "Acción"].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(e => <tr key={e.event_id}><td className="title-cell"><small>{e.event_id}</small><br/><Link href={`/caso/${e.event_id}/`}>{e.title}</Link>{e.synthetic ? <Badge value="SINTÉTICO"/> : null}{e.is_recirculated ? <p>Recirculada</p> : null}</td><td className="numeric">{e.priority.score}<br/><Badge value={e.priority.tier}/></td><td><Badge value={e.evidence_status}/></td><td>{readable(e.topic)}</td><td>{panama(e.last_published)}<br/><small>Detección: {panama(e.first_detected)}</small></td><td>{e.source_dna.publications}</td><td>{e.source_dna.max_possible_independent}</td><td>{e.source_dna.confirmed_independent}</td><td>{e.has_conflicts ? "Sí · pendiente" : "No registrado"}</td><td style={{minWidth:220}}>{e.recommended_action}</td></tr>)}</tbody></table></div>{!filtered.length ? <p className="empty">No hay eventos que coincidan con los filtros.</p> : null}</section><section><p className="eyebrow">Dos ejes independientes</p><h2>Prioridad × Evidencia</h2><p className="muted">Conteos de los eventos visibles con tus filtros.</p><div className="table-wrap matrix"><table><thead><tr><th>Atención</th>{states.map(s => <th key={s}>{readable(s)}</th>)}</tr></thead><tbody>{["alto", "medio", "bajo"].map(t => <tr key={t}><td><Badge value={t}/></td>{states.map(s => <td key={s}>{filtered.filter(e => e.priority.tier === t && e.evidence_status === s).length}</td>)}</tr>)}</tbody></table></div></section></>;
}
