import Link from "next/link";
import { events, getCase } from "@/lib/data";
import { Heading, Notices } from "@/components/shared";
export const metadata = {title: "Recorrido del jurado"};
export default function Tour() {
  const rows = events();
  const example = rows.find(row => row.package_mode !== null && getCase(row.event_id).official_evidence.length > 0);
  const conflict = rows.find(row => row.has_conflicts);
  const steps = [
    ["Elige un tema", "En la agenda, observa la prioridad y el estado de evidencia por separado. El puntaje explica qué revisar primero; no confirma el titular.", "/#agenda", "Ver la agenda"],
    ["Comprueba el sustento", "Abre una cita y revisa su fuente, campo y período. Distingue el contexto oficial de una confirmación de la noticia.", example ? `/caso/${example.event_id}/#evidencia` : "/", "Examinar evidencia"],
    ["Inspecciona el borrador", "Lee el brief, el guion y el texto para redes. Cada oración distingue hechos, declaraciones e inferencias y permite inspeccionar sus citas. Observa el modo y modelo utilizados.", example ? `/caso/${example.event_id}/#producir` : "/", "Ver el paquete editorial"],
    ["Revisa antes de decidir", "Consulta los vacíos y verificaciones pendientes. Registra una revisión en la ficha: indica el estado, la persona revisora y una justificación. Descarga el recibo; el historial queda en este navegador.", example ? `/caso/${example.event_id}/#revision` : "/", "Ver la revisión humana"],
    ["Prueba sus límites", "Pregunta por una cifra que el corpus no contiene: verás una abstención y la información que hace falta. En Pruebas y métricas puedes comprobar el alcance de cada medición.", "/consultas/#sin-respuesta", "Ver una abstención"],
  ];
  return <><Heading section="Primera visita" title="De un tema a un borrador revisable">Recorrido sugerido de unos 3 minutos para explorar SCAYL sin explicación del equipo. Puedes abrir cada paso y volver aquí desde la navegación.</Heading><aside className="card"><h2>¿Para quién y para qué?</h2><p>Para editores y periodistas que necesitan decidir qué investigar. SCAYL organiza titulares públicos, explica prioridades, conecta evidencia y prepara borradores con citas. La persona conserva la decisión editorial.</p><p className="warning">Demo con datos congelados: no monitorea noticias ni ejecuta IA en vivo. Los borradores son salidas guardadas de IA local o plantillas; cada resultado lo identifica. Las consultas libres buscan en el snapshot público; si no hay red, los ejemplos guardados siguen disponibles.</p></aside><Notices/><ol className="tour-steps">{steps.map(([title, description, href, action], i) => <li className="card" key={title}><span className="step-number" aria-hidden="true">0{i+1}</span><div><h2>{title}</h2><p>{description}</p><Link className="button" href={href}>{action} →</Link></div></li>)}</ol>{conflict ? <section className="card"><h2>Una comprobación adicional</h2><p>Cuando aparecen cifras incompatibles, SCAYL conserva ambas versiones y muestra la verificación pendiente.</p><Link className="button secondary" href={`/caso/${conflict.event_id}/#conflictos`}>Examinar un conflicto →</Link></section> : null}<section className="card"><h2>Qué deberías poder explicar al terminar</h2><p>Por qué se prioriza un tema, de dónde sale una afirmación, qué no está confirmado y qué debe revisar una persona antes de usar el borrador.</p><Link className="button" href="/trust-lab/">Ver pruebas y métricas →</Link><p className="muted" style={{marginTop:12}}>El simulador es una exploración opcional de los pesos. La documentación y presentación del reto están en el repositorio. Notion es opcional según la aclaración oficial C-03.</p></section></>;
}
